apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" $ }}-fs-{{ .name }}
  labels:
    app: {{ template "openldap.name" $ }}
    chart: {{ template "openldap.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- if $.Values.extraLabels }}
{{ toYaml $.Values.extraLabels | indent 4 }}
{{- end }}
data:
  {{- (.Files.Glob "bootstrap/**.ldif").AsConfig | nindent 2 }}
---
